# ------ root_path/dataset_name ------
root_path: './$DATA'


# ------ Load Cache and Features ------
load_cache: False
# load_pre_feat: False
# load_pre_feat_raw: False

# load_cache: True
load_pre_feat: True
load_pre_feat_raw: True


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [50, 25]
search_step: [200, 20]

init_beta: 8
init_alpha: 4


# ------ Basic Config ------
dataset: 'cwru'
# shots: 16
shots_list: [1, 2, 4, 8, 16]
backbone: 'ViT-B/16'
fintune_dataset: 'pu'
working_condition: [0hp, 1hp, 2hp, 3hp]
num_classes: 10

lr: 0.001
augment_epoch: 5
train_epoch_list: [25, 25, 25, 25, 25]
# epoch=25 for all shots

# ------ LORA r value, default 0 means do not use LORA ------
lora_r: 16